###############################################################################
# v1.0
#
# docker-compose up -d
#
# REQURIED:
# * make sure you have the .env file as well
#
# author: Nick Yeoman
# website: https://www.NickYeoman.com/blog/linux/docker-getting-started/
###############################################################################

version: '3'

services:

  traefik:
    # Docker hub: https://hub.docker.com/_/traefik/
    # Example: https://docs.traefik.io/user-guides/docker-compose/basic-example/
    image: traefik:v2.1.3
    container_name: traefik
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      #Basic auth: https://docs.traefik.io/middlewares/basicauth/
      - "traefik.http.middlewares.test-auth.basicauth.users=${DC_USER}:${DC_PASS}"
