---
###############################################################################
# Set timezone and install docker, configure git
#
# Version 2.0
# author: Nick Yeoman
# website: https://www.nickyeoman.com/blog/linux/ansible-getting-started/
###############################################################################

- hosts: all

###############################################################################
# Varibles, change to your requirements
###############################################################################
  vars:
    v_username: nick
    v_email: c@nickyeoman.com

###############################################################################
# Timezone
###############################################################################
  tasks:
  - name: Set Timezone to Vancouver
    timezone: name=America/Vancouver

###############################################################################
# Docker
###############################################################################
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: apt update
    apt:
      update_cache: yes

  - name: Install Docker and my docker dependancies
    apt:
      state: latest
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker.io
      - docker-compose
      - python-apt

  - name: Allow defined user to use docker, usermod -aG docker $USER
    user:
      name: "{{ v_username}}"
      shell: /bin/bash
      group: "{{ v_username}}"
      groups: docker, sudo, adm, dip, plugdev, lxd
      state: present

  ###############################################################################
  # Git
  ###############################################################################

  - name: Configure Git
    git_config:
      name="{{ item.name }}"
      scope=global
      value="{{ item.value }}"
    with_items:
      - {name: "user.name",  value: "{{ v_username}}" }
      - {name: "user.email", value: "{{ v_email}}" }
      - {name: "ui.color",   value: "True" }
