---

###############################################################################
# Set timezone and install docker, configure git
#
# Version 1.1
# author: Nick Yeoman
# website: https://www.NickYeoman.com/blog/getting-started-with-ansible/
###############################################################################

- hosts: all

###############################################################################
# Varibles, change to your requirements
###############################################################################
  vars:
    v_username: nick
    v_hostname: nixbuntu
    v_email: c@nickyeoman.com
    gitpath: /home/nick/Git

###############################################################################
# Timezone
###############################################################################
  tasks:
  - name: Set Timezone to Vancouver
    timezone: name=America/Vancouver

###############################################################################
# Docker
###############################################################################
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: apt update
    apt:
      update_cache: yes

  - name: Install Docker and my docker dependancies
    apt:
      state: latest
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker.io
      - docker-compose
      - python-apt

  - name: Allow defined user to use docker, usermod -aG docker $USER
    user:
      name: "{{ v_username}}"
      shell: /bin/bash
      group: "{{ v_username}}"
      groups: docker, sudo, adm, dip, plugdev, lxd
      state: present

###############################################################################
# Hostname
###############################################################################
  - name: Change hostname
    hostname:
      name: "{{ v_hostname }}"
      use: debian

  ###############################################################################
  # Git
  ###############################################################################

  - name: Configure Git
    git_config:
      name="{{ item.name }}"
      scope=global
      value="{{ item.value }}"
    with_items:
      - {name: "user.name",  value: "{{ v_username}}" }
      - {name: "user.email", value: "{{ v_email}}" }
      - {name: "ui.color",   value: "True" }

  - name: Ensure directory exists
    file:
      path: "{{ gitpath }}"
      state: directory
      mode: '0750'
      owner: "{{ v_username }}"
      group: "{{ v_username }}"

  - name: Clone ansible public repo
    git:
      repo: git@github.com:nickyeoman/ansible-public.git
      dest: "{{ gitpath }}/ansible-public"
      key_file: "{{ gitkey }}"
      accept_hostkey: yes
      version: master
      update: no
