---

###############################################################################
# v1.1
#
# wget https://fbot.co/ansiblexfce -O installxfce.yml
# ansilbe-playbook -i localhost, -u root -k installxfce.yml
#
# Goals:
# - install xfce
# - Configure virtualbox
#
# author: Nick Yeoman
# website: https://www.NickYeoman.com/blog/linux/install-xfce-on-ubuntu-server-1804/
###############################################################################

# not meant to use a hosts file
- hosts: all

  tasks:
  - name: install xfce4
    apt:
      state: latest
      pkg:
      - xfce4
      - firefox
      # Screensavers
      - xscreensaver 
      - xscreensaver-gl-extra 
      - xscreensaver-data-extra

  - name: grab a wallpaper, we will set it later
    get_url:
      url: https://w.wallhaven.cc/full/od/wallhaven-odk1w5.jpg
      dest: /usr/share/backgrounds/xfce/picard-unmotivater.jpg
      checksum: sha256:91558bb4f20dd5ef752889f01266e62dad0b3425e6632c1ae8be4e46d1fa2df0
      
